### PR TITLE
[run_all] Syntactic cleaning.

### PR DESCRIPTION
**Pull request by zim-tis**
Quick and superficial cleaning of the syntax in run_all. Nothing deeper than that.

### CODE REVIEW

**Comment by zim-tis** [comment]
I did only a basic syntactic cleaning of the script, except the changes that would impact the script globally or functionally, namely:
- change the non-standard indentation level from 3 to 2;
- add dots at the end of sentences;
- use an array for `analysis_list` instead of a regular variable.

I did not do any functional changes, but there are many weird things in the script:
- the license choice is dubious, although I'm not a license expert;
- it does not honor the `NO_COLOR` variable;
- no option have a long format;
- the arguments for `-a` and `-n` are not sanitized;
- the script prevents the user to access parallel options, and then works really hard to restore some of them. For example, `parallel` can keep logs for each run but the scripts rebuilds its own system to do it.

It would probably be worth to have the script reviewed by a developer.

**Comment by okorach** [comment]
Thank you @zim-tis for the review.
Most of your comments are valid by I don't have the time to review for now.

May I ask you to give your identity ? I am a bit curious of whom may review TrustInSoft demos ?

**Comment by okorach** [comment]
OKay, I should have figured out Stephane !

**Comment by zim-tis** [comment]
> OKay, I should have figured out Stephane !

It is I indeed.

>  I am a bit curious of whom may review TrustInSoft demos ?

For this script specifically anybody that is used to bash script and the company style. If the question is a general one, you can always ask for reviews in the dedicated channel of the internal chat; developers and customer success people are here for that.

**Pull request merged**
